version: 1
updates:
    # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
     
  - package-ecosystem: "yarn"
    directory: "/" 
    schedule:
      interval: "daily"
    commit-message:
      prefix: "yarn"
    labels:
      - "dependencies"
